FOGL-3237 Prevent setting numAssets less than 1
foglamp/foglamp-south-benchmark pull request #23
Opened 2019-08-30 12:34 UTC by MarkRiddoch

2019-08-30 13:02 UTC, praveen-garg requested changes
resulting in a loop of assets creation..

2019-09-11 12:03 UTC, praveen-garg commented
1) `curl -X PUT http://localhost:8081/foglamp/category/bench/numAssets -d '{"default":"1","order": "2","type": "string","value": "0","description": "Number of unique assets to simulate","displayName": "Number Of Assets" }' `

Service gets shutdown and schedule remains enabled! 
Logs:

```
FATAL: Unhandled exception raised in south plugin reconfigure(), The value of numAssets must be greater than 0
FATAL: Unrecoverable failure during South plugin reconfigure, south service exiting...
```



2) `curl -X PUT http://localhost:8081/foglamp/category/bench/numAssets -d '{"default":"1","order": "2","type": "string","value": "-1","description": "Number of unique assets to simulate","displayName": "Number Of Assets" }' `

resulting in a loop of assets creation.

2019-10-22 15:41 UTC, MarkRiddoch commented
> 1. `curl -X PUT http://localhost:8081/foglamp/category/bench/numAssets -d '{"default":"1","order": "2","type": "string","value": "0","description": "Number of unique assets to simulate","displayName": "Number Of Assets" }' `
> 
> Service gets shutdown and schedule remains enabled!

I don't see this is a problem

> Logs:
> 
> ```
> FATAL: Unhandled exception raised in south plugin reconfigure(), The value of numAssets must be greater than 0
> FATAL: Unrecoverable failure during South plugin reconfigure, south service exiting...
> ```
> 
> 1. `curl -X PUT http://localhost:8081/foglamp/category/bench/numAssets -d '{"default":"1","order": "2","type": "string","value": "-1","description": "Number of unique assets to simulate","displayName": "Number Of Assets" }' `
> 
> resulting in a loop of assets creation.
It appears the API does not implement the minimum and maximum rules, a Jira has been raised for that, in the meantime a rule has been added which will be honoured by the current implementation of the API.

2019-10-23 08:52 UTC, praveen-garg approved these changes

2019-10-23 11:31 UTC, merged